### ISSUE TITLE
Change from submitting consolidated expenses to full expenses

### ISSUE THREAD

**Issue by PhilipHodgson** [hmrc/income-tax-mtd-changelog#10] opened 2021-08-23 08:13 UTC
A business switches from submitting _consolidated expenses_ to _full expenses_ during the course of an accounting period.

How should that be corrected at the period end?

I tried submitting a BSAS adjustment with a negative amount for _consolidatedExpenses_ and positive amounts for the other expense items, but that causes a RULE_BOTH_EXPENSES_SUPPLIED error. I'm not clear if that message relates to the adjustments, or the amounts after the adjustments. The latter would be just fine. It is impossible to determine this with the fixed JSON returned in the sandbox.

**Comment by hmrc-api-team** [comment] 2023-04-06 11:16
Closing this issue for now. It looks like the issue is because the test/sandbox environment currently doesn't maintain any state and only sends canned responses. We do have a project underway to support dynamic and stateful responses, in order to make the development and testing process easier.  I've passed along your description of the problem to the team involved.

**Closed by hmrc-api-team** 2023-04-06 11:16 UTC
