### ISSUE TITLE
404 when amending a self-employment periodic update

### ISSUE THREAD

**Issue by ac000** [hmrc/income-tax-mtd-changelog#6] opened 2021-08-12 15:12 UTC
When calling [Amend a self-employment periodic update](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/self-assessment-api/2.0#Amend%20a%20self-employment%20periodic%20update) I'm getting a 404 "Not Found"

Here's the list periods for the self-employment business (as returned by _./obligations/details/MZ200944B/income-and-expenditure?typeOfBusiness=self-employment)

```
       period_id              start         end          due      met
 ---------------------------------------------------------------------
  2018-04-06_2018-07-05     2018-04-06   2018-07-05   2018-08-05   t
  2018-07-06_2018-10-05     2018-07-06   2018-10-05   2018-11-05   f
  2018-10-06_2019-01-05     2018-10-06   2019-01-05   2019-02-05   f
  2019-01-06_2019-04-05     2019-01-06   2019-04-05   2019-05-06   f
```

When trying to update _2018-04-06_2018-07-05_

```JSON
[
    {
        "status_code": 404,
        "status_str": "Not Found",
        "url": "https://test-api.service.hmrc.gov.uk/self-assessment/ni/MZ200944B/self-employments/XVIS04154145764/periods/2018-04-06_2018-07-05",
        "method": "PUT",
        "xid": null,
        "result": null
    }
]
```

This is likely related to #3 where most things seem to currently be using a tax year of 2018-19 but somewhere behind the scenes 2020-21 is in use.

If I try to update the period **2020-04-06_2020-07-05** (where does that come from?!), I.e

```
https://test-api.service.hmrc.gov.uk/self-assessment/ni/MZ200944B/self-employments/XVIS04154145764/periods/2020-04-06_2020-07-05
```

then it works as expected.

**Comment by hmrc-api-team** [comment] 2023-04-06 11:10
Closing this issue for now. It looks like the issue is because the test/sandbox environment currently doesn't maintain any state and just sends canned responses. We do have a project underway to support dynamic and stateful responses, in order to make the development and testing process easier.

**Closed by hmrc-api-team** 2023-04-06 11:10 UTC
